## Stages by grouping
jobs:
  job1:
    requires: [~pr, ~commit]
    image: node:14
    steps:
      - init: echo 'init'
  job2:
    requires: [~pr, ~commit]
    image: node:14
    steps:
      - init: echo 'init'
  job3:
    requires: [~pr, ~commit]
    image: node:14
    steps:
      - init: echo 'init'
  job4:
    requires: [~pr, ~commit]
    image: node:14
    steps:
      - init: echo 'init'
  job5:
    requires: [job1]
    image: node:14
    steps:
      - init: echo 'init'
  job6:
    requires: [job2]
    image: node:14
    steps:
      - init: echo 'init'
  job7:
    requires: [job3]
    image: node:14
    steps:
      - init: echo 'init'
  job8:
    requires: [job4]
    image: node:14
    steps:
      - init: echo 'init'

stages:
  starfish:
    jobs: [job3, job4]
    description: "Prod deploy jobs"
  seahorse:
    jobs: [job3, job4]
    description: "Prod deploy jobs"
    color: '#00FFFF'